name: Kubernetes Deploy Action
description: A GitHub Action for deploying a Kubernetes application to an internal Parallax Digital cluster.
runs:
  using: node20
  main: ./bootstrap-shim.js
inputs:
  event:
    description: The event that triggered the workflow.
    required: true
    default: ${{ github.event_name }}
  configuration:
    description: The Kubernetes configuration containing all contexts to deploy to.
    required: false
  resources:
    description: The path to the resources to deploy.
    required: true
  namespace:
    description: The Kubernetes namespace to deploy to.
    required: true
    default: ${{ github.event.repository.name }}-${{ github.event.deployment.environment }}
